version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.2
    expose:
      - "8080"
    deploy:
      replicas: 4
    networks:
      - api-network
    environment:
      PING_LISTEN_PORT: 8080

  proxy:
    image: nginx:alpine
    ports:
      - 8081:80
    networks:
      - api-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

networks:
  api-network:
    driver: bridge
