# Stage 1
FROM node as builder
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json", "./"]
RUN ["npm", "ci"]
COPY ["index.ts", "tsconfig.json", "./"]
RUN ["npm", "run", "tsc"]
RUN ["npm", "ci", "--production"]

# Stage 2
FROM node:alpine
WORKDIR /usr/src/app
RUN ["addgroup", "-S", "fastify"]
RUN ["adduser", "-S", "fastify", "-G", "fastify"]
COPY --from=builder --chown=fastify:fastify ["/usr/src/app/build", "./build"]
COPY --from=builder --chown=fastify:fastify ["/usr/src/app/node_modules", "./node_modules"]
USER fastify
ENTRYPOINT ["node", "./build/index"]
EXPOSE 3000/tcp
